language: python
python:
  - "2.7.12"
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  allow_failures:
    - python: "2.7.12"
    - python: "3.5"

install:
  - pip install nose codecov
  - python setup.py install

script:
  - "nosetests --with-coverage --cover-package=charset_normalizer test/*.py"

after_success:
  - codecov
